[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about"
  status = 200
  force = true

[[redirects]]
  from = "/project/"
  to = "/project/"
  status = 200
  force = false
  query = {path = ":path"}

[[redirects]]
  from = "/contact"
  to = "/contact"
  status = 200
  force = true

